baseURL = "https://yfrobotics.github.io"
languageCode = "en-us"
title = "YF Robotics Laboratory"

[params]
  favicon = ""
  subtitle = "Building a Brighter Future with Robots."
  custom_css = ["/css/custom.css"]

  
[markup.goldmark.renderer]
  unsafe = true
    
